### ISSUE TITLE
Trigger config refresh via ZookeeperTreeCachePropertySource.

### ISSUE THREAD

**Issue by idcmp** [spring-cloud/spring-cloud-zookeeper#49]
I'd love something like:

    @ZookeeperProperty(name="helpful-url",auto-start=false)
    private Provider<String> helpfulUrlProvider;
    ...
        LOG.debug("You can find help at: {}", helpfulUrlProvider.get());

Since it's a Provider, calls to .get would automatically have the "latest" value from ZK via the ZookeeperTreeCachePropertySource. The property would automatically be expected to live under one of the contexts. auto-start false would indicate that all wiring and looking up would be performed on the first query instead of bean wiring time.

    @EphemeralNode(name="helpful-url",auto-start=false,default-value="http://localhost:${server.port}")
    private EphemeralNode helpfulUrl;
    ....
    // maybe after leader election
    ephemeralNode.start();
    ephemeralNode.set("update value");

EphemeralNode would be lifecycle aware and close on predestroy, and if auto-start=true, call start() during post create.

**Comment by spencergibb** [comment]
No need for something like `@ZookeeperProperty`+`Provider`. With spring boot/cloud  [@ConfigurationProperties](http://docs.spring.io/spring-boot/docs/1.3.0.RC1/reference/htmlsingle/#boot-features-external-config-typesafe-configuration-properties) object can be refreshed with new values.  (ie if you POST to `/refresh`). What is missing is to trigger a refresh if using [ZookeeperTreeCachePropertySource](https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-config/src/main/java/org/springframework/cloud/zookeeper/config/ZookeeperTreeCachePropertySource.java).

**Comment by efenderbosch** [comment]
Is there a general design you'd like to see so that beans can subscribe to property value changes via TreeCacheEvents? Would this tie in with the existing ``@RefreshScope``? We're looking for this functionality and can probably contribute it back.

**Comment by spencergibb** [comment]
It should tie in with existing `/refresh` functionality from spring-cloud-commons. See [here](https://github.com/toast2e/spring-cloud-consul/blob/master/spring-cloud-consul-config/src/main/java/org/springframework/cloud/consul/config/watch/ConsulConfigurationListener.java) for a current PR for consul.

**Comment by efenderbosch** [comment]
Does this sound reasonable? Have ``ZookeeperTreeCachePropertySource`` implement ``TreeCacheListener`` and register itself with the backing ``TreeCache``. When a ``TreeCacheEvent`` happens, call ``RefreshEndpoint#refresh``. ``RefreshEndpoint`` could be wired up in ``ZookeeperConfigBootstrapConfiguration``.

The only problem I see with this approach is that the entire context is refreshed with any property change, instead of just the affected beans.

It might be possible to grab all beans tagged with ``@ConfigurationProperties`` and introspect their path from the annotation and only refresh the bean that matches ``TreeCacheEvent.getData().getPath()`` via ``RefreshScope.refresh(String name)`` instead of ``RefreshScope.refreshAll()``. Although I don't know how to figure out the full path for nested configurations.

**Comment by efenderbosch** [comment]
Ok, I have this working as I described in the bottom of previous post. If a ``@ConfigurationProperties`` is also tagged with ``@RefreshScope`` then that bean, and only that bean, will be refreshed when a ``TreeCacheEvent`` is received and the event's path matches the bean's path.

The only problem is that I need to register the child application context, not the bootstrap context, with each ``ZookeeperTreeCachePropertySource``. I've got an ugly hack that walks through the PropertySources after initialization, but I'm sure there has to be a better way.
