### ISSUE TITLE
spring.cloud.zookeeper.enabled=false is not enough to disable Zookeeper

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-zookeeper#89]
You have to also pass `spring.cloud.zookeeper.discovery.enabled=false` which makes no sense. Also `RibbonZookeeperAutoConfiguration` is used then.

**Comment by damnhandy** [comment]
The problem is in the `ZookeeperConfigAutoConfiguration` class here:

https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/spring-cloud-zookeeper-config/src/main/java/org/springframework/cloud/zookeeper/config/ZookeeperConfigAutoConfiguration.java#L40

It's using `matchIfMissing = true` which will always result in the condition evaluating to true no matter what the value is. I ran into the same issue the other and saw this. I'd have to wonder if that's there for a specific reason, or if it was just a typo?

**Comment by spencergibb** [comment]
@damnhandy no, `spring.cloud.zookeeper.config.watcher.enabled=false` works. The `matchIfMissing=true` attribute means, if the attributed isn't defined, assume true. In other words, on by default. There's no conditional on `spring.cloud.zookeeper.enabled` in `ZookeeperConfigAutoConfiguration.java` and discovery.

**Comment by spencergibb** [comment]
ping @marcingrzejszczak

**Comment by marcingrzejszczak** [comment]
Thanks :)
