### ISSUE TITLE
I get configuration of zk by spring-cloud-zookeeper,but the configuration will change.

### ISSUE THREAD

**Issue by jonelee05** [spring-cloud/spring-cloud-zookeeper#98]
I get configuration of zookeeper by spring-cloud-zookeeper,but the configuration will change.I don't want restart my application to get the changed value.how can i do?

**Comment by spencergibb** [comment]
Have you tried posting to `/refresh`?

**Comment by jonelee05** [comment]
/refresh? please get me some simple demo or document,thanks.

**Comment by spencergibb** [comment]
http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_endpoints

**Comment by jonelee05** [comment]
@spencergibb Follow the document.no web environment in my application,so use refreshAll in RefreshScope class.but not get the changed value of zk.
configuration class
@Configuration
public class TinyLanguage {
    @Bean
    public LanguageBean getLanguageBean() {
        return new LanguageBean();
    }
}
bean class
@RefreshScope
public class LanguageBean {
    @Value("${tiny_language}")
    private String language;

    public String getLanguage() {
        return language;
    }
}

**Comment by erecarte** [comment]
Hi @jonelee05 I believe that the problem is that you have the `@RefreshScope` annotation in the wrong place. You must have the annotation together with where you are declaring the bean. So you must do either of these:

```java
@Bean
@RefreshScope
public LanguageBean getLanguageBean() {
    return new LanguageBean();
}
``` 

or

```java
@RefreshScope
@Service
public class LanguageBean {
```

By the way, I don't think it's documented anywhere, but if you have the actuator dependency in the classpath, then you don't need to refresh manually as it does it automatically every time you update a property in Zookeeper. There is even a property to enable/disable it: `spring.cloud.zookeeper.config.watcher.enabled`. @spencergibb is this something that should be added to the docs?

**Comment by spencergibb** [comment]
@erecarte it's not documented

**Comment by damnhandy** [comment]
Actually, isn't it covered here in the core Spring Cloud docs:

http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_refresh_scope

Granted, the docs don't provide code examples, but it is covered.

**Comment by jonelee05** [comment]
@erecarte  tks for you suggest.

**Comment by liq05** [comment]
Use spring cloud config，This question is not exist.
